services:
  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=modulith'
      - 'POSTGRES_PASSWORD=modulith'
      - 'POSTGRES_USER=modulith'
    ports:
      - '5432:5432'
    volumes:
      - /home/nelson/tmp/modulith/postgres_modulith:/var/lib/postgresql/data
volumes:
  postgres: