spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modulith
    username: modulith
    password: modulith
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  modulith:
    republish-outstanding-events-on-restart: true

